### PR TITLE
Add Linda Nichols

### PR DESCRIPTION
**Pull request by lynnaloo**

### CODE REVIEW

**Comment by jlooper** [comment]
hi, please add your name alphabetically (the first instance). thanks!

**Comment by ladyleet** [comment]
@lynnaloo just a reminder!

**Comment by ladyleet** [comment]
@jlooper resolved for lynn

**Comment by lynnaloo** [comment]
Thank you! I had this on my list to fix and hadn't circled back yet.

**Comment by ladyleet** [comment]
@lynnaloo 👍

**Pull request merged**
